spring:
  jackson:
    time-zone: "America/Sao_Paulo"
  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:flowpay_db}}
    username: ${DB_USER:${POSTGRES_USER:postgres}}
    password: ${DB_PASSWORD:${POSTGRES_PASSWORD:postgres}}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
  sql:
    init:
      mode: never