DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS agent;
DROP TABLE IF EXISTS queue;

CREATE TABLE queue (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    team VARCHAR(50) NOT NULL,
    max_capacity INT NOT NULL,
    version BIGINT DEFAULT 0
);

CREATE TABLE agent (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    team VARCHAR(50) NOT NULL,
    current_load INT DEFAULT 0,
    version BIGINT DEFAULT 0,
    max_capacity INT NOT NULL DEFAULT 3
);

CREATE TABLE ticket (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    ticket_number BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    chat_ref VARCHAR(255),
    subject VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    error_msg VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    queue_id UUID REFERENCES queue(id),
    agent_id UUID REFERENCES agent(id),
    version BIGINT DEFAULT 0
);
